services:
  # ui:
  #   container_name: "${CONTAINER_NAME}-ui"
  #   build:
  #     context: packages/ui
  #     dockerfile: Dockerfile.dev
  #   env_file:
  #     - .env
  #   depends_on:
  #       - api
  api:
    container_name: "${CONTAINER_NAME}-api"
    working_dir: "/app"
    build:
      context: "packages/server"
      dockerfile: "Dockerfile.dev"
      # ENV variables are not automatically available to the Dockerfile
      args:
        - BUILD_VERSION="${VERSION}"
    env_file:
      - ".env"
    volumes:
      - "./packages/server:/app"
      # cache go mod download data
      - "go-mod-data:/go/pkg/mod"
      # cache go install data
      - "go-bin-data:/gobin"
      # cache prisma binaries
      - "prisma-data:/root/.cache/prisma/binaries/cli"
    networks:
        - "milton"

volumes:
  go-mod-data:
  go-bin-data:
  prisma-data:
#   node_modules:

networks:
  milton:

