// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	FlowerPot        string
	Job              string
	Log              string
	Unit             string
	PrismaMigrations string
}{
	FlowerPot:        "FlowerPot",
	Job:              "Job",
	Log:              "Log",
	Unit:             "Unit",
	PrismaMigrations: "_prisma_migrations",
}
